#!/bin/sh
set -eu

DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
cd "$DIR"

export BTCC20_AGENT_HOST="${BTCC20_AGENT_HOST:-127.0.0.1}"
export BTCC20_AGENT_PORT="${BTCC20_AGENT_PORT:-28798}"
export BTCC20_AGENT_RPC_URL="${BTCC20_AGENT_RPC_URL:-http://127.0.0.1:28476}"
export BTCC20_AGENT_RPC_USER="${BTCC20_AGENT_RPC_USER:-user}"
export BTCC20_AGENT_RPC_PASSWORD="${BTCC20_AGENT_RPC_PASSWORD:-pass}"
export BTCC20_AGENT_WALLET="${BTCC20_AGENT_WALLET:-miner}"
export BTCC20_AGENT_DRY_RUN="${BTCC20_AGENT_DRY_RUN:-0}"
export BTCC20_AGENT_ORD="${BTCC20_AGENT_ORD:-$DIR/ord.exe}"

node agent.mjs
